from django.urls import path
from . import views

urlpatterns = [
    path('', views.user_login, name='login'),
    path('accounts/login/', views.user_login, name='login'),
    path('home/', views.home, name='home'),
    path('change-password/', views.change_password, name='change_password'),
    path('ttowner/', views.ttowner_list, name='ttowner_list'),
    path('ttowner/add/', views.ttowner_add, name='ttowner_add'),
    path('register/', views.register_user, name='register_user'),
    path('contractor/add/', views.contractor_add, name='contractor_add'),
    path('contractor/list/', views.contractor_list, name='contractor_list'),
    path('company/add/', views.company_add, name='company_add'),
    path('company/list/', views.company_list, name='company_list'),
    path('ttowner/edit/<int:id>/', views.ttowner_edit, name='ttowner_edit'),
    path('ttowner/delete/<int:id>/', views.ttowner_delete, name='ttowner_delete'),
    path('contractors/edit/<int:pk>/', views.contractor_edit, name='edit_contractor'),
    path('contractors/delete/<int:pk>/', views.contractor_delete, name='delete_contractor'),
    path('companies/edit/<int:pk>/', views.company_edit, name='edit_company'),
    path('companies/delete/<int:pk>/', views.company_delete, name='delete_company'),
    path('ttmaster/', views.ttmaster_list, name='ttmaster_list'),
    path('ttmaster/add/', views.ttmaster_add, name='ttmaster_add'),
    path('ttmaster/edit/<int:id>/', views.ttmaster_edit, name='ttmaster_edit'),
    path('ttmaster/delete/<int:id>/', views.ttmaster_delete, name='ttmaster_delete'),
    path('product/', views.product_list, name='product_list'),         
    path('product/add/', views.product_create, name='product_create'),  
    path('product/edit/<int:pk>/', views.product_edit, name='product_edit'), 
    path('product/delete/<int:pk>/', views.product_delete, name='product_delete'), 
    path('citymaster/', views.citymaster_list, name='citymaster_list'),
    path('citymaster/create/', views.citymaster_create, name='citymaster_create'),
    path('citymaster/edit/<int:id>/', views.citymaster_edit, name='citymaster_edit'),
    path('citymaster/delete/<int:id>/', views.citymaster_delete, name='citymaster_delete'),
    path('fares/', views.fare_list, name='fare_list'),
    path('fares/add/', views.fare_create, name='fare_create'),
    path('fares/edit/<int:pk>/', views.fare_edit, name='fare_edit'),
    path("fare/edit/<int:id>/", views.fare_edit, name="fare_edit"),
    path("fare/delete/<int:id>/", views.fare_delete, name="fare_delete"),
]
