# Generated by Django 5.2 on 2025-09-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=256)),
                ('user_level', models.IntegerField()),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('last_login_date', models.DateTimeField(blank=True, null=True)),
                ('last_password_change_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
