# Generated by Django 5.2 on 2025-09-05 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0004_passwordhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTOwnerMaster',
            fields=[
                ('IDNumber', models.AutoField(primary_key=True, serialize=False)),
                ('OwnerName', models.CharField(max_length=200)),
                ('Address', models.TextField()),
                ('City', models.CharField(max_length=100)),
                ('PANGIR_Number', models.CharField(blank=True, max_length=50, null=True)),
                ('Opening_Balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('Opg_Balance_Type', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], default='D', max_length=1)),
                ('If_Insurance', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('Number_Of_TT', models.IntegerField(default=0)),
                ('TDS_Rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('If_Maintenance', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('Updated_On', models.DateTimeField(default=django.utils.timezone.now)),
                ('Updated_By', models.CharField(max_length=150)),
            ],
        ),
    ]
