# Generated by Django 5.2 on 2025-09-07 06:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0005_ttownermaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorMaster',
            fields=[
                ('IdNumber', models.AutoField(primary_key=True, serialize=False)),
                ('ContractorName', models.CharField(max_length=150)),
                ('Address', models.CharField(max_length=500)),
                ('PhoneNumber_1', models.CharField(blank=True, max_length=15, null=True)),
                ('PhoneNumber_2', models.CharField(blank=True, max_length=15, null=True)),
                ('MobileNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('EmailID', models.CharField(blank=True, max_length=100, null=True)),
                ('TPTR_Code', models.CharField(blank=True, max_length=10, null=True)),
                ('Bill_Prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('BillNumber', models.IntegerField(default=0)),
                ('If_Own', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('Updated_On', models.DateTimeField(default=django.utils.timezone.now)),
                ('Updated_By', models.CharField(max_length=10)),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.ttownermaster')),
            ],
        ),
    ]
