# Generated by Django 5.2 on 2025-09-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0006_contractormaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractormaster',
            name='City',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
