# Generated by Django 5.2 on 2025-09-07 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0007_alter_contractormaster_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractormaster',
            old_name='City',
            new_name='CityName',
        ),
    ]
