# Generated by Django 5.2 on 2025-09-07 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0008_rename_city_contractormaster_cityname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractormaster',
            old_name='CityName',
            new_name='City',
        ),
    ]
