# Generated by Django 5.2 on 2025-09-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0009_rename_cityname_contractormaster_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('IdNumber', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=20)),
                ('OpeningBalance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('OpeningBalanceType', models.CharField(blank=True, max_length=1, null=True)),
                ('Bill_LU', models.CharField(blank=True, max_length=1, null=True)),
                ('If_Hire', models.CharField(blank=True, max_length=1, null=True)),
                ('Updated_On', models.DateTimeField(auto_now=True)),
                ('Updated_By', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
