# Generated by Django 5.2 on 2025-09-13 12:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0010_companymaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerMasterNew',
            fields=[
                ('OwnerCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('OwnerName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TTMasterNew',
            fields=[
                ('IDNumber', models.AutoField(primary_key=True, serialize=False)),
                ('TT_Registration_Number', models.CharField(max_length=15, unique=True)),
                ('If_Own_TT', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('TT_KL_Size', models.PositiveIntegerField()),
                ('Date_Of_Induction', models.DateField()),
                ('Date_Of_Release', models.DateField(blank=True, null=True)),
                ('TT_Make', models.CharField(max_length=20)),
                ('TT_Model', models.CharField(max_length=20)),
                ('Engine_Serial_Number', models.CharField(max_length=15)),
                ('Chassis_Number', models.CharField(max_length=15)),
                ('Whether_Dedicated', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('Explosive_Licence_Number', models.CharField(blank=True, max_length=15, null=True)),
                ('Explosive_Licence_Validity_Date', models.DateField(blank=True, null=True)),
                ('Chemical_Licence_Validity_Date', models.DateField(blank=True, null=True)),
                ('Insurance_Policy_Number', models.CharField(max_length=15)),
                ('Insurance_Validity_Date', models.DateField()),
                ('Insurance_Company', models.CharField(max_length=20)),
                ('RTO_Due_Date', models.DateField()),
                ('PAF_Due_Date', models.DateField()),
                ('NP_Due_date', models.DateField()),
                ('National_Permit_1', models.CharField(blank=True, max_length=10, null=True)),
                ('National_Permit_2', models.CharField(blank=True, max_length=10, null=True)),
                ('National_Permit_3', models.CharField(blank=True, max_length=10, null=True)),
                ('National_Permit_4', models.CharField(blank=True, max_length=10, null=True)),
                ('If_Hire', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('If_Maintenance', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('KM_Reading', models.PositiveIntegerField()),
                ('Updated_On', models.DateTimeField(default=django.utils.timezone.now)),
                ('Update_By', models.CharField(max_length=10)),
                ('Owner_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.ownermasternew')),
            ],
        ),
    ]
