# Generated by Django 5.2 on 2025-09-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0011_ownermasternew_ttmasternew'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('IDNumber', models.AutoField(primary_key=True, serialize=False)),
                ('Owner_Code', models.CharField(max_length=5)),
                ('Owner_Name', models.CharField(max_length=255)),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Short_Name', models.CharField(max_length=4)),
                ('If_Ejectt', models.CharField(max_length=1)),
                ('Updated_OPn', models.DateTimeField()),
                ('Updated_By', models.CharField(max_length=10)),
            ],
        ),
    ]
