# Generated by Django 5.2 on 2025-09-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0012_productmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citymaster',
            fields=[
                ('id_number', models.AutoField(primary_key=True, serialize=False)),
                ('city_code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=30)),
                ('t_zone', models.CharField(max_length=15)),
                ('terminal', models.CharField(max_length=10)),
                ('loc_code', models.CharField(max_length=5)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=10)),
            ],
        ),
    ]
