# Generated by Django 5.2 on 2025-09-17 18:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0013_citymaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='FareMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('owner_code', models.CharField(max_length=5)),
                ('fare_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('if_nett', models.CharField(max_length=1)),
                ('fare_type', models.CharField(max_length=1)),
                ('rtd_kms', models.DecimalField(decimal_places=0, max_digits=4)),
                ('product_type', models.CharField(max_length=1)),
                ('range1_fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('range2_fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('range3_fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('range4_fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('range1_discount_fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('range2_discount_fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('range3_discount_fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('range4_discount_fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('if_hire', models.CharField(max_length=1)),
                ('discount_fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('shortage_full_deduction', models.CharField(max_length=1)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.CharField(max_length=10)),
                ('fare_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fare_company_set', to='Masters.companymaster')),
                ('fare_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fare_from_set', to='Masters.citymaster')),
                ('fare_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fare_product_set', to='Masters.productmaster')),
                ('fare_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fare_to_set', to='Masters.citymaster')),
            ],
        ),
    ]
