# Generated by Django 5.2 on 2025-09-17 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0014_faremaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faremaster',
            name='discount_fare',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='faremaster',
            name='fare_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.companymaster'),
        ),
        migrations.AlterField(
            model_name='faremaster',
            name='fare_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fare_from', to='Masters.citymaster'),
        ),
        migrations.AlterField(
            model_name='faremaster',
            name='fare_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.productmaster'),
        ),
        migrations.AlterField(
            model_name='faremaster',
            name='fare_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fare_to', to='Masters.citymaster'),
        ),
        migrations.AlterField(
            model_name='faremaster',
            name='range1_discount_fare',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='faremaster',
            name='range1_fare',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='faremaster',
            name='range2_discount_fare',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='faremaster',
            name='range2_fare',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='faremaster',
            name='range3_discount_fare',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='faremaster',
            name='range3_fare',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='faremaster',
            name='range4_discount_fare',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='faremaster',
            name='range4_fare',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='faremaster',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
