# Generated by Django 5.2 on 2025-09-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0015_alter_faremaster_discount_fare_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faremaster',
            name='updated_by',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
