# Generated by Django 5.2 on 2025-09-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0016_alter_faremaster_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citymaster',
            name='t_zone',
        ),
    ]
